In [1]:
import pandas as pd

# Series

In [2]:
data = [1,2,3,4,5]

In [3]:
s = pd.Series(data)

In [4]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
index = ['linha' + str(i) for i in range(5)]

In [6]:
index

['linha0', 'linha1', 'linha2', 'linha3', 'linha4']

In [7]:
s = pd.Series(data = data, index=index)

In [8]:
s

linha0    1
linha1    2
linha2    3
linha3    4
linha4    5
dtype: int64

In [9]:
data = {'linha' + str(i) : i + 1 for i in range(5)}

In [10]:
data

{'linha0': 1, 'linha1': 2, 'linha2': 3, 'linha3': 4, 'linha4': 5}

In [11]:
s = pd.Series(data)
s

linha0    1
linha1    2
linha2    3
linha3    4
linha4    5
dtype: int64

In [12]:
s1 = s + 2
s1

linha0    3
linha1    4
linha2    5
linha3    6
linha4    7
dtype: int64

In [15]:
s2 = s + s1
s2

linha0     4
linha1     6
linha2     8
linha3    10
linha4    12
dtype: int64

In [18]:
df1 = pd.DataFrame({'A': {'X': 1}, 'B': {'X': 2}})
df2 = pd.DataFrame({'C': {'X': 3}, 'D': {'X': 4}})
pd.concat([df1, df2])

     A    B    C    D
X  1.0  2.0  NaN  NaN
X  NaN  NaN  3.0  4.0

In [19]:
dados = [('A', 'B'), ('C', 'D')]
df = pd.DataFrame(dados, columns = ['L1', 'L2'],  index = ['C1', 'C2'])
df

   L1 L2
C1  A  B
C2  C  D

In [26]:
dados = [[1, 2, 3], [4, 5, 6]]
index = 'X,Y'.split(',')
columns = list('CBA')[::-1]
df = pd.DataFrame(dados, index, columns)
df

   A  B  C
X  1  2  3
Y  4  5  6

In [21]:
dados = {'A': {'X': 1, 'Y': 3}, 'B': {'X': 2, 'Y': 4}}
df = pd.DataFrame(dados)
df

   A  B
X  1  2
Y  3  4