# TAREFA 2 - MONTAGEM DO CONJUNTO DE DADOS

* Nome do aluno: Dgeison Serrão Peixoto
* Matrícula: 230395
* E-mail: 1366415@sga.pucminas.br
* Professor: Victor Sales Silva
* Disciplina: Preparação, Orquestração e Fluxos Contínuo de dados
* Atividade: Exercício 1 - Fundamentos da preparação de dados

## EXERCÍCIO

Você trabalha como analista de dados em uma empresa que quer entender como a satisfação dos clientes varia com vendas e clima.

Você recebeu os seguintes arquivos:

* clientes.xml: Dados cadastrais de clientes e sua satisfação
* vendas.csv: Registros de vendas realizadas por cliente
* clima.json: Histórico de clima por data e cidade

O objetivo é unificar essas bases, padronizar os dados e responder algumas perguntas analíticas.

Importação das bibliotecas

In [2]:
import pandas as pd
import json
import xml.etree.cElementTree as ET

### 1. Coleta
* Carregue os arquivos em Dataframes
* Como ler cada um dos arquivos?
  - Quais bibliotecas mais adequadas para cada tipo?

In [5]:
dfvendas= pd.read_csv('vendas.csv')
dfclima = pd.read_json('clima.json')
dfclientes = pd.read_xml('clientes.xml')

In [6]:
# Imprime um título e mostra as 5 primeiras linhas de cada DataFrame

print("--- DataFrame de Vendas (vendas.csv) ---")
display(dfvendas.head())

print("\n--- DataFrame de Clima (clima.json) ---")
display(dfclima.head())

print("\n--- DataFrame de Clientes (clientes.xml) ---")
display(dfclientes.head())

--- DataFrame de Vendas (vendas.csv) ---

   id_cliente  data_venda   valor
0         113  2023-09-23  242.04
1         143  2024-07-10  294.44
2         174  2024-10-02  160.05
3         137  2024-08-05  269.39
4         150  2023-12-27  167.25

--- DataFrame de Clima (clima.json) ---

         data     cidade  temperatura
0  2023-08-01  São Paulo           27
1  2023-08-02  São Paulo           32
2  2023-08-03  São Paulo           20
3  2023-08-04  São Paulo           27
4  2023-08-05  São Paulo           25

--- DataFrame de Clientes (clientes.xml) ---

    id                               nome     cidade  satisfacao
0  100                     mariana araújo  São Paulo           3
1  101                             Carla   São Paulo           3
2  102                              Tiago  São Paulo           5
3  103                     Daniel Martins  São Paulo           3
4  104    Carla  Melo  Pereira  Almeida    São Paulo           2

### 2. Preparação
* Padronize, limpe e junte os dados
   - Garanta que os nomes das cidades estejam no mesmo formato
   - Junte os dados das três fontes
   - Converta os tipos de dados dos dataframes analisados para o formato adequado

In [14]:

dfvendas['data_venda'] = pd.to_datetime(dfvendas['data_venda'], errors='coerce')
dfclima['data'] = pd.to_datetime(dfclima['data'], errors='coerce')

dfclientes['nome'] = dfclientes['nome'].astype('string')
dfclientes['cidade'] = dfclientes['cidade'].astype('string')

In [15]:
dfvendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  5 non-null      int64
 1   data_venda  5 non-null      datetime64[ns]
 2   valor       5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 252.0 bytes

### 3. Armazenamento
* Crie uma pasta chamada silver e salve os dados preparados nela.
    - Salve os dados em um formato uniforme para uso (sugestão → parquet)

### 4. Análise

* Responda as seguintes perguntas (fique a vontade para a melhor forma de apresentar os resultados)
   - Média de satisfação de cliente por cidade
   - Menor, maior, soma e média do valor pago por cidade
   - Total de clientes por cidade
   - Total de vendas por cidade, mês
   - Total de vendas que ocorrem por cidade e por faixa de temperaturas
     - temperaturas altas (acima de 28º)
     - baixas (abaixo de 22º)
     - amenas (entre 23º e 27º)?

#### 4.1. Média de satisfação de cliente por cidade

#### 4.2. Menor, maior, soma e média do valor pago por cidade

#### 4.3. Total de clientes por cidade

#### 4.4. Total de vendas por cidade e ano/mês

#### 4.5. Total de vendas que ocorrem por cidade e por faixa de temperaturas
     - temperaturas altas (acima de 28º)
     - baixas (abaixo de 22º)
     - amenas (entre 23º e 27º)?

### 5. Ações
* Com base nos resultados, quais conclusões você consegue tirar do conteúdo analisado?
* O que pode ser automatizado a partir dos dados analisados?

Resposta (texto)